# Generated by Django 4.2.11 on 2024-04-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Usuarios", new_name="Usuario",),
    ]
